# Generated by Django 6.0.3 on 2026-03-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(default='VClass Student', max_length=50)),
                ('reference_image_path', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=128)),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
                ('impersonation_flags', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.student')),
            ],
        ),
    ]
