# Generated by Django 5.0.3 on 2026-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(default='objective', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='examlog',
            name='answers_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='examlog',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='examlog',
            name='grade_letter',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='examlog',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examlog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examlog',
            name='status',
            field=models.CharField(default='started', max_length=20),
        ),
        migrations.AddField(
            model_name='examlog',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examlog',
            name='timeline_json',
            field=models.TextField(default='[]'),
        ),
    ]
