# Generated by Django 5.0.3 on 2026-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_student_is_active_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
