# Generated by Django 5.0.3 on 2026-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_to',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='specific_students',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('ALL', 'All Students'), ('FST', 'Faculty of Science & Technology'), ('FBA', 'Faculty of Business Administration'), ('FLAW', 'Faculty of Law'), ('FED', 'Faculty of Education'), ('FICT', 'Faculty of ICT'), ('FHSS', 'Faculty of Humanities & Social Sciences'), ('FMED', 'Faculty of Medicine')], default='FST', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
