# Generated by Django 5.0.3 on 2026-07-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_exam_assigned_to_exam_specific_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlog',
            name='question_scores_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('ALL', 'All Students'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('DS', 'Data Science'), ('IS', 'Information Systems')], default='SE', max_length=10),
        ),
    ]
